### ISSUE TITLE
meteoris-core fails to install on current Mac os

### ISSUE THREAD

**Issue by GitaWei** [meteoris/meteoris#11]
meteoris-core now fails to install on Mac due to using older kadira:flow-router (2.11) which relies on grateful-fs.  Version 2.12 has fixed the issue by removing support for graceful-fs.

Fix if you want people to use it.   None of your tutorials work.

(ref: https://github.com/meteor/meteor/issues/9310)

$ meteor add meteoris:core
 => Errors while adding packages:             
                                              
While loading package kadira:flow-router@2.11.0:
error: Command failed:
/Users/ldavison/.meteor/packages/meteor-tool/.1.8.0_1.fvr6qi.h6n7i++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
rebuild --update-binary
module.js:549
throw err;
^

Error: Cannot find module 'internal/util/types'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at evalmachine.<anonymous>:31:26
at Object.<anonymous>
(/Users/ldavison/.meteor/packages/kadira_flow-router/.2.11.0.1fjlnd6.dzbc++os+web.browser+web.cordova/npm/node_modules/fs-extra/node_modules/graceful-fs/fs.js:11:1)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional
logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ldavison/.npm/_logs/2018-12-18T01_17_55_408Z-debug.log
module.js:549
throw err;
^

Error: Cannot find module 'internal/util/types'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at evalmachine.<anonymous>:31:26
at Object.<anonymous>
(/Users/ldavison/.meteor/packages/kadira_flow-router/.2.11.0.1fjlnd6.dzbc++os+web.browser+web.cordova/npm/node_modules/fs-extra/node_modules/graceful-fs/fs.js:11:1)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional
logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ldavison/.npm/_logs/2018-12-18T01_17_55_408Z-debug.log

**Comment by fabioaraujo121** [comment]
Try to update your `kadira:flow-router`.

`meteor update kadira:flow-router`

The flow-router had some bad dependencies...
