### ISSUE TITLE
ReferenceError: meteorInstall is not defined

### ISSUE THREAD

**Issue by ShawnSantiago** [meteoris/meteoris#6]
Hi I kept getting this error 

`W20160502-17:40:48.425(-4)? (STDERR)          
W20160502-17:40:48.426(-4)? (STDERR) /Users/shawnsantiago/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160502-17:40:48.426(-4)? (STDERR)                        throw(ex);
W20160502-17:40:48.427(-4)? (STDERR)                              ^
W20160502-17:40:48.427(-4)? (STDERR) ReferenceError: meteorInstall is not defined
W20160502-17:40:48.427(-4)? (STDERR)     at /Users/shawnsantiago/Google Drive/Projects/Meteor/BloggingApp/myBlogApp/.meteor/local/build/programs/server/packages/meteoris_user.js:22:15
W20160502-17:40:48.427(-4)? (STDERR)     at /Users/shawnsantiago/Google Drive/Projects/Meteor/BloggingApp/myBlogApp/.meteor/local/build/programs/server/packages/meteoris_user.js:680:3
W20160502-17:40:48.427(-4)? (STDERR)     at /Users/shawnsantiago/Google Drive/Projects/Meteor/BloggingApp/myBlogApp/.meteor/local/build/programs/server/boot.js:283:10
W20160502-17:40:48.427(-4)? (STDERR)     at Array.forEach (native)
W20160502-17:40:48.427(-4)? (STDERR)     at Function._.each._.forEach (/Users/shawnsantiago/.meteor/packages/meteor-tool/.1.3.2_4.lbyo5v++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160502-17:40:48.427(-4)? (STDERR)     at /Users/shawnsantiago/Google Drive/Projects/Meteor/BloggingApp/myBlogApp/.meteor/local/build/programs/server/boot.js:133:5`

**Comment by radiegtya** [comment]
is not yet compatible with meteor 1.3.2
